name: CI

on:
 push:
  branches: [master]
 pull_request:
  branches: [master]

jobs:
 build:
  runs-on: ubuntu-latest
  defaults:
   run:
    working-directory: ./frontend
  strategy:
   matrix:
    node-version: [14.x, 15.x]
  steps:
   - uses: actions/checkout@v2
   - name: Setup Node.js v${{ matrix.node-version }}
     uses: actions/setup-node@v1
     with:
      node-version: ${{ matrix.node-version }}
   - name: npm install and test
     run: |
      npm ci
      npm run build
      npm test
